language: python

matrix:
  include:
    - name: "backend: unit test"
      dist: bionic
      python: "3.7"
      install: pip install -r dispatcher/backend/requirements.txt
      before_script:
        - cd dispatcher/backend/src
        - export PYTHONPATH=$PWD
      script: pytest tests/unit
    - name: "backend: integration test"
      dist: bionic
      python: "3.7"
      services: mongodb
      install:
        - pip install -r dispatcher/backend/requirements.txt
        - pip install codecov pytest pytest-cov
      before_script:
        - cd dispatcher/backend/src
        - export PYTHONPATH=$PWD
        - python -c "from utils.database import Initializer; Initializer.initialize()"
      script: pytest -c tests/integration/pytest.ini tests/ --cov=./
      after_success:
        - codecov
