language: python

matrix:
  include:
    - name: "backend: unit test"
      dist: xenial
      python: "3.7"
      install: pip install -r dispatcher/backend/requirements.txt
      before_script:
        - cd dispatcher/backend/src
        - export PYTHONPATH=$PWD
      script: pytest tests/unit
    - name: "backend: integration test"
      dist: xenial
      python: "3.7"
      services: mongodb
      install:
        - pip install -r dispatcher/backend/requirements.txt
        - pip install codecov pytest pytest-cov
      before_script:
        - cd dispatcher/backend/src
        - export PYTHONPATH=$PWD
        - export MONGO_HOSTNAME=localhost
        - python prestart.py
      script: pytest tests/integration --cov=./
      after_success:
        - codecov
