version: '3'
services:
    rabbit:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        hostname: zimfarm
        environment:
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=admin_pass
            - DISPATCHER_USERNAME=dispatcher
            - DISPATCHER_PASSWORD=dispatcher_pass
        volumes:
            - ./docker_data/rabbitmq/data:/var/lib/rabbitmq
        ports:
            # debug only, for using management plugin
            - 8081:15672
            # change external port(7285) to something else if needed
            - 7285:5672
        restart: always
        labels:
            - com.chrisshwli.zimfarm.name="rabbit"

    proxy:
        build:
            context: ./proxy
            dockerfile: Dockerfile
        links:
            # - frontend
            - backend
        depends_on:
            # - frontend
            - backend
        ports:
            - "8080:80"
        restart: always
        labels:
            - com.chrisshwli.zimfarm.name="proxy"

#    frontend:
#        build:
#            context: ./frontend
#            dockerfile: Dockerfile
#        volumes:
            # debug only
            # - ./frontend/src:/app/src

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=admin_pass
            - DISPATCHER_USERNAME=dispatcher
            - DISPATCHER_PASSWORD=dispatcher_pass
            - DEBUG=True
        links:
            - rabbit
        volumes:
            # - ./backend/app:/app
            - ./docker_data/backend:/data
        depends_on:
            - rabbit
        restart: always
        labels:
            - com.chrisshwli.zimfarm.name="backend"
