version: '2'
services:
  rabbit:
    image: rabbitmq:3-management
    extends:
      file: config.yml
      service: base
    hostname: zimfarm
    restart: always
    logging:
      driver: none
    volumes:
      - ./docker_data/rabbitmq:/var/lib/rabbitmq
    ports:
      # communication with worker celery instance
      - 28001:5672
  mongo:
    image: mongo:latest
    volumes:
      - ./docker_data/mongo:/data/db
    restart: always
    logging:
      driver: none
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    extends:
      file: config.yml
      service: base
    environment:
      - DEBUG=True
    volumes:
      - ./backend/:/app
    links:
      - rabbit
      - mongo
    depends_on:
      - rabbit
      - mongo
    ports:
      - 28000:80
    restart: always