version: '3'
services:
    rabbit:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        hostname: zimfarm
        environment:
            - ADMIN_PASSWORD=admin_pass
            - DISPATCHER_USERNAME=dispatcher
            - DISPATCHER_PASSWORD=dispatcher_pass
        ports:
            # debugging only, for using management plugin
            - 8081:15672
        volumes:
            - ./docker_data/rabbitmq/data:/var/lib/rabbitmq
        logging:
            driver: "none"
    proxy:
        build:
            context: ./proxy
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        links:
            - backend
            - frontend
        depends_on:
            - backend
            - frontend
        logging:
            driver: "none"
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - DISPATCHER_USERNAME=dispatcher
            - DISPATCHER_PASSWORD=dispatcher_pass
            - DEBUG=True
        ports:
            # debug only
            - "8088:80"
        links:
            - rabbit
        volumes:
            # development only
            - ./backend/app:/app
            - ./docker_data/backend:/dispatcher_data
        depends_on:
            - rabbit
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            # development only
            - ./frontend/src:/app/src