version: '3'
services:
    rabbit:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        hostname: zimfarm
        environment:
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=admin_pass
            - DISPATCHER_USERNAME=dispatcher
            - DISPATCHER_PASSWORD=dispatcher_pass
        ports:
            # debug only, for using management plugin
            - 8081:15672
        volumes:
            - ./docker_data/rabbitmq/data:/var/lib/rabbitmq
        logging:
            driver: "json-file"

    proxy:
        build:
            context: ./proxy
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        links:
            # - frontend
            - backend
        depends_on:
            # - frontend
            - backend
        logging:
            driver: "json-file"

#    frontend:
#        build:
#            context: ./frontend
#            dockerfile: Dockerfile
#        volumes:
            # debug only
            # - ./frontend/src:/app/src

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=admin_pass
            - DISPATCHER_USERNAME=dispatcher
            - DISPATCHER_PASSWORD=dispatcher_pass
            - DEBUG=True
        # ports:
            # - "8088:80"
        links:
            - rabbit
        volumes:
            # - ./backend/app:/app
            - ./docker_data/backend:/data
        depends_on:
            - rabbit
