version: '2'
services:
  rabbit:
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./docker_data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 28001:5672
    hostname: rabbit
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./docker_data/mongo:/data/db
    logging:
      driver: none
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 28000:80
    links:
      - rabbit
      - mongo
    depends_on:
      - rabbit
      - mongo
    environment:
      - INIT_USERNAME=admin
      - INIT_PASSWORD=admin_pass