version: '3'
services:
    rabbit:
      build:
        context: ./rabbitmq
        dockerfile: Dockerfile
      hostname: zimfarm
      environment:
        - ADMIN_PASSWORD=admin_pass
        - DISPATCHER_PASSWORD=dispatcher_pass
      ports:
        # debugging only, for using management plugin
        - 8081:15672
      volumes:
        - ./docker_data/rabbitmq/data:/var/lib/rabbitmq
      logging:
        driver: "json-file"