name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dispatcher/backend/requirements.txt
        pip install pytest
    - name: black code formatting check
      uses: jpetrucciani/black-check@master
      with:
        path: '.'
    - name: Test with pytest
      env:
        PYTHONPATH: $GITHUB_WORKSPACE/dispatcher/backend/src
      run: pytest tests/unit
